import { useEffect, useState } from 'react'
import Head from 'next/head'

import Card from '../components/Card'
import DefaultLayout from '../layouts/Default'

const Cats = () => {
  const [cats, setCats] = useState([])

  useEffect(async () => {
    ;(async () => {
      const res = await fetch('api/cats')
      const data = await res.json()
      setCats(data)
    })()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DefaultLayout>
        <div className='container mt-5'>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '40px' }}>
            {cats.map((cat) => (
              <Card
                key={cat.id}
                name={cat.name}
                id={cat.id}
                phone={cat.phone}
                email={cat.email}
                image={cat.image}
              />
            ))}
          </div>
        </div>
      </DefaultLayout>
    </>
  )
}

export default Cats
