import Head from 'next/head'

import Jumbotron from '../components/Jumbotron'
import DefaultLayout from '../layouts/Default'

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DefaultLayout>
        <Jumbotron />
      </DefaultLayout>
    </main>
  )
}
